### ISSUE TITLE
BUG: "Command 'SpaceBox Enable UI Enhancer' resulted in an error"

### ISSUE THREAD

**Issue by NeilPandya** [amnweb/SpaceBox-UI-Enhancer#2]
After installing `SpaceBox UI Enhancer` and trying to enable it via the command palette, I receive the following error:
![ErrorSpaceBoxUIEnhancer](https://github.com/user-attachments/assets/741b562f-2263-4d6e-a40c-f7ef260c20d1)
# SpaceBox UI
```yaml
SpaceBox UI Enhancer: v0.0.61
Published: 2024-01-21, 01:44:05
Last released: 2024-02-19, 02:47:26
Last updated: 2024-10-21, 12:50:42
```
# VSCodium
```yaml
Version: 1.94.2
Release: 24286
Commit: 62f778783c52510c94e687de293bc2ad230f9a67
Date: 2024-10-12T20:14:54.465Z
Electron: 30.5.1
ElectronBuildId: undefined
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Linux x64 6.8.0-47-generic
```
# System Specs
```
                                           neil@FractalNorth 
           `.:/ossyyyysso/:.               ----------------- 
        .:oyyyyyyyyyyyyyyyyyyo:`           OS: Kubuntu trixie/sid (noble) x86_64 
      -oyyyyyyyodMMyyyyyyyysyyyyo-         Kernel: 6.8.0-47-generic 
    -syyyyyyyyyydMMyoyyyydmMMyyyyys-       Uptime: 3 hours, 27 mins 
   oyyysdMysyyyydMMMMMMMMMMMMMyyyyyyyo     Packages: 2432 (dpkg), 19 (flatpak-system) 
 `oyyyydMMMMysyysoooooodMMMMyyyyyyyyyo`    Shell: bash 5.2.21 
 oyyyyyydMMMMyyyyyyyyyyyysdMMysssssyyyo    Resolution: 1920x1080 @ 164.92Hz 
-yyyyyyyydMysyyyyyyyyyyyyyysdMMMMMysyyy-   DE: Plasma 5.27.11 [KF5 5.115.0] [Qt 5.15.13] (x11) 
oyyyysoodMyyyyyyyyyyyyyyyyyyydMMMMysyyyo   WM: KWin 
yyysdMMMMMyyyyyyyyyyyyyyyyyyysosyyyyyyyy   Theme: klassy [KDE/Qt], Breeze [GTK2/3] 
yyysdMMMMMyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy   Icons: BeautySolar [KDE/Qt/GTK2/3] 
oyyyyysosdyyyyyyyyyyyyyyyyyyydMMMMysyyyo   Cursor: Breeze_Snow [KDE/GTK2/3] 
-yyyyyyyydMysyyyyyyyyyyyyyysdMMMMMysyyy-   Terminal: konsole 
 oyyyyyydMMMysyyyyyyyyyyysdMMyoyyyoyyyo    Terminal Font: Noto Mono 14 
 `oyyyydMMMysyyyoooooodMMMMyoyyyyyyyyo     CPU: AMD Ryzen 9 5950X (32) @ 3.4GHz 
   oyyysyyoyyyysdMMMMMMMMMMMyyyyyyyyo      GPU: NVIDIA GeForce RTX 3090 
    -syyyyyyyyydMMMysyyydMMMysyyyys-       Memory: 7.66 GiB / 31.24 GiB (24%) 
      -oyyyyyyydMMyyyyyyysosyyyyo-         Network: Wifi 
        ./oyyyyyyyyyyyyyyyyyyo/.           Bluetooth: Intel Corp. AX200 
           `.:/oosyyyysso/:.`              BIOS: American Megatrends Inc. 5.17 (03/18/2024) 
```
